// "use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Header from "@/components/header";
import { AuthProvider } from "@/context/authContext";
import { Suspense } from "react";
import Loading from "./loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { registerLicense } from "@syncfusion/ej2-base";
import Footer from "@/components/footer";
import { SocketProvider } from "@/context/socketContext";
import { DestinationProvider } from "@/context/destinationContext";
registerLicense(process.env.NEXT_PUBLIC_SYNCFUSION_LICENSE_KEY || "");

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<Loading />}>
          <AuthProvider>
            <SocketProvider>
              <DestinationProvider>
                <Header />
                {children}
                <Footer />
                <Toaster />
              </DestinationProvider>
            </SocketProvider>
          </AuthProvider>
        </Suspense>
      </body>
    </html>
  );
}
